In [1]:
import numpy as np
import cv2
before1 = np.float32([[346, 623],[915,401],[714, 155],[169,92]])
after1 = np.float32([[196,396],[388,396],[388,267],[196,267]])

M1 = cv2.getPerspectiveTransform(before1,after1)
M1


array([[ 3.04152892e-03,  1.82407614e-01,  1.69835984e+02],
       [-2.95909021e-01,  7.01168088e-01,  2.40420095e+02],
       [-9.49469069e-04,  1.25231345e-03,  1.00000000e+00]])

In [2]:
before2 = np.float32([[942,709],[100,500],[197,306],[983,174]])
after2 = np.float32([[375,90],[375,264],[304,264],[304,90]])

M2 = cv2.getPerspectiveTransform(before2,after2)
M2

array([[ 1.07120712e+01,  1.36392767e+01, -1.87081143e+03],
       [-4.03074220e-01,  1.88963717e+00,  3.33359281e+03],
       [ 3.16939051e-02,  2.37680673e-02,  1.00000000e+00]])

In [3]:
before3 = np.float32([[733,718],[203,542],[415,220],[935,131]])
after3 = np.float32([[439,388],[294,388],[294,272],[439,272]]) 

M3 = cv2.getPerspectiveTransform(before3,after3)
M3

array([[-4.98283981e+01, -4.23554973e+01,  1.51268349e+04],
       [-2.58291582e+01, -4.78288334e+01,  7.48401733e+03],
       [-7.93668243e-02, -8.47342837e-02,  1.00000000e+00]])

In [4]:
#모델 yolo4
import tensorflow as tf
import os

def download_model(model_type):
    server_prefix = 'https://omnomnom.vision.rwth-aachen.de/data/metrabs'
    model_zippath = tf.keras.utils.get_file(
        origin=f'{server_prefix}/{model_type}.zip',
        extract=True, cache_subdir='models')
    model_path = os.path.join(os.path.dirname(model_zippath), model_type)
    return model_path

model = tf.saved_model.load(download_model('metrabs_rn18_y4'))
    

In [8]:
import cv2
image = cv2.imread('C:/Users/Leeyourack/jookyoung/image/1.test_image/peo3.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


In [9]:
pred = model.detect_poses(image, skeleton='smpl_24')

In [16]:
pred['poses2d'].numpy()[:,7:9]

array([[[434.09357, 465.93677],
        [473.65503, 475.3583 ]],

       [[323.9566 , 447.51376],
        [325.25552, 456.21518]],

       [[572.61115, 424.22998],
        [554.3382 , 415.16852]]], dtype=float32)

In [5]:
def draw_keypoints(frame,keypoints):
    shaped = np.squeeze(keypoints)
    
    for p in shaped:
        x,y = p
        if x > 0:
            cv2.circle(frame,(int(x),int(y)), 4, (0,255,0), -1)

In [6]:
def loop_through_people(frame ,keypoints_with):
    for person in keypoints_with:
        draw_keypoints(frame,person)

In [34]:
all=pred['poses2d'].numpy()
for i, person in enumerate(all):
    print(person[0][0]+person[2][0])

962.94257
653.8557
1112.7269


In [30]:
print('뒷 왼쪽발',pred['poses2d'].numpy()[:,7]) #뒷 왼쪽발
print('뒷 오른쪽발',pred['poses2d'].numpy()[:,8]) #뒷 오른쪽발
print('앞 왼쪽발',pred['poses2d'].numpy()[:,10]) # 앞 왼쪽발
print('앞 오른쪽발',pred['poses2d'].numpy()[:,11]) # 앞 오른쪽발
print('꼭지',pred['poses2d'].numpy()[:,10]/2+pred['poses2d'].numpy()[:,11]/2) # 꼭지

뒷 왼쪽발 [[434.09357 465.93677]
 [323.9566  447.51376]
 [572.61115 424.22998]]
뒷 오른쪽발 [[473.65503 475.3583 ]
 [325.25552 456.21518]
 [554.3382  415.16852]]
앞 왼쪽발 [[421.0414  469.6874 ]
 [336.45953 452.16455]
 [567.03015 431.85123]]
앞 오른쪽발 [[474.6752  480.8792 ]
 [343.96637 466.2968 ]
 [543.4464  421.52954]]
꼭지 [[447.8583  475.28333]
 [340.21295 459.23068]
 [555.2383  426.69037]]


In [ ]:

ROI_image = cv2.imread('C:/Users/Leeyourack/jookyoung/image/0.ROI_image/pre_image_final.jpg')
cv2.polylines(ROI_image,)

In [ ]:
trans_foot_1 = M1@(front_x_1 , front_y_1 , 1)
            trans_foot_1 = trans_foot_1/trans_foot_1[2]
            trans_x_1 = trans_foot_1[0]
            trans_y_1 = trans_foot_1[1]

In [30]:
trans_list1=[]
def mat1(M1,x,y):
    
    trans_1 = M1@(x,y,1)
    trans_1 = trans_1/trans_1[2]
    tx_1= trans_1[0]
    ty_1 = trans_1[1]
    trans_list1.append([tx_1,ty_1])
    print(trans_list1)
    

trans_list2=[]
def mat2(M2,x,y):
    
    trans_2 = M2@(x,y,1)
    trans_2 = trans_2/trans_2[2]
    tx_2= trans_2[0]
    ty_2 = trans_2[1]
    trans_list2.append([tx_2,ty_2])
    

trans_list3=[]
def mat3(M3,x,y):
    
    trans_3 = M3@(x,y,1)
    trans_3 = trans_3/trans_3[2]
    tx_3= trans_3[0]
    ty_3 = trans_3[1]
    trans_list3.append([tx_3,ty_3])
    

In [ ]:
pts1 = np.array([[left_x_1,left_y_1],[right_x_1,right_y_1],[front_x_1,front_y_1]], np.int32)

In [10]:
M1

array([[ 3.04152892e-03,  1.82407614e-01,  1.69835984e+02],
       [-2.95909021e-01,  7.01168088e-01,  2.40420095e+02],
       [-9.49469069e-04,  1.25231345e-03,  1.00000000e+00]])

In [44]:
print('1',mat2(M2,10,10))
print('2',mat2(M2,10,100))
print('3',trans_list2)



1 None
2 None
3 [[-1046.749843071012, 2153.8762109717745], [-108.22700616133523, 952.563061428718], [-1046.749843071012, 2153.8762109717745], [-108.22700616133523, 952.563061428718], [-1046.749843071012, 2153.8762109717745], [-108.22700616133523, 952.563061428718], [-1046.749843071012, 2153.8762109717745], [-108.22700616133523, 952.563061428718], [-1046.749843071012, 2153.8762109717745], [-108.22700616133523, 952.563061428718], [-1046.749843071012, 2153.8762109717745], [-108.22700616133523, 952.563061428718], [-1046.749843071012, 2153.8762109717745], [-108.22700616133523, 952.563061428718]]


In [51]:
#카메라 3대  원하는 영역에서 검출된 발만 mapping
#방향

import cv2
import datetime
import os

from shapely.geometry import Point
from shapely.geometry.polygon import Polygon


ROI_image = cv2.imread('C:/Users/Leeyourack/jookyoung/image/0.ROI_image/pre_image_final.jpg')
#ROI_image2 = cv2.imread('C:/Users/Leeyourack/jookyoung/image/0.ROI_image/pre_image_final.jpg')

def writeVideo():
    global ROI_image
    global ROI_image2
    
    #현재시간 가져오기
    currentTime = datetime.datetime.now()
    
    #RTSP를 불러오는 곳
    video_capture1 = cv2.VideoCapture("C:/Users/Leeyourack/jookyoung/video/1.test_video/new_test1.avi")
    video_capture2 = cv2.VideoCapture("C:/Users/Leeyourack/jookyoung/video/1.test_video/new_test2.avi")
    video_capture3 = cv2.VideoCapture("C:/Users/Leeyourack/jookyoung/video/1.test_video/new_test3.avi")
    

    # 웹캠 설정
    video_capture1.set(3, 800)  # 영상 가로길이 설정
    video_capture1.set(4, 600)  # 영상 세로길이 설정
    # 웹캠 설정
    video_capture2.set(3, 800)  # 영상 가로길이 설정
    video_capture2.set(4, 600)  # 영상 세로길이 설정
    # 웹캠 설정
    video_capture3.set(3, 800)  # 영상 가로길이 설정
    video_capture3.set(4, 600)  # 영상 세로길이 설정
    
    # 가로 길이 가져오기
    streaming_window_width = int(video_capture1.get(3))
    # 세로 길이 가져오기
    streaming_window_height = int(video_capture1.get(4))  

   
    
    
    #현재 시간을 '년도 달 일 시간 분 초'로 가져와서 문자열로 생성
    fileName = str(currentTime.strftime('%Y %m %d %H %M %S'))

    #파일 저장하기 위한 변수 선언
    path1 = 'C:/Users/Leeyourack/jookyoung/video/2.detect_video/test1.avi'
    #파일 저장하기 위한 변수 선언
    path2 = 'C:/Users/Leeyourack/jookyoung/video/2.detect_video/test2.avi'
    #파일 저장하기 위한 변수 선언
    path3 = 'C:/Users/Leeyourack/jookyoung/video/2.detect_video/test3.avi'
    #파일 저장하기 위한 변수 선언
    path4 = 'C:/Users/Leeyourack/jookyoung/video/2.detect_video/test4-2.avi'
    #파일 저장하기 위한 변수 선언
    path5 = 'C:/Users/Leeyourack/jookyoung/video/2.detect_video/test5.avi'
    
    # DIVX 코덱 적용 # 코덱 종류 # DIVX, XVID, MJPG, X264, WMV1, WMV2
    # 무료 라이선스의 이점이 있는 XVID를 사용
    fourcc = cv2.VideoWriter_fourcc('X', 'V', 'I', 'D')
    fps = 20
    # 비디오 저장
    # cv2.VideoWriter(저장 위치, 코덱, 프레임, (가로, 세로))
    out1 = cv2.VideoWriter(path1, fourcc, fps, (streaming_window_width, streaming_window_height))
    out2 = cv2.VideoWriter(path2, fourcc, fps, (streaming_window_width, streaming_window_height))
    out3 = cv2.VideoWriter(path3, fourcc, fps, (streaming_window_width, streaming_window_height))
    out4 = cv2.VideoWriter(path4, fourcc, fps, (1280, 540))
    out5 = cv2.VideoWriter(path5, fourcc, fps, (640, 480))

    while True:
        ROI_image2 = cv2.imread('C:/Users/Leeyourack/jookyoung/image/0.ROI_image/pre_image_final.jpg')
        ret1, frame1 = video_capture1.read()
        ret2, frame2 = video_capture2.read()
        ret3, frame3 = video_capture3.read()
        
        img1 = frame1.copy()
        img2 = frame2.copy()
        img3 = frame3.copy()

        results1 = model.detect_poses(img1, skeleton='smpl_24')
        keypoints_with1 = results1['poses2d'].numpy()
        results2 = model.detect_poses(img2, skeleton='smpl_24')
        keypoints_with2 = results2['poses2d'].numpy()
        results3 = model.detect_poses(img3, skeleton='smpl_24')
        keypoints_with3 = results3['poses2d'].numpy()


        '''print('뒷 왼쪽발',pred['poses2d'].numpy()[:,7]) #뒷 왼쪽발
        print('뒷 오른쪽발',pred['poses2d'].numpy()[:,8]) #뒷 오른쪽발
        print('앞 왼쪽발',pred['poses2d'].numpy()[:,10]) # 앞 왼쪽발
        print('앞 오른쪽발',pred['poses2d'].numpy()[:,11]) # 앞 오른쪽발
        print('꼭지',pred['poses2d'].numpy()[:,10]/2+pred['poses2d'].numpy()[:,11]/2) # 꼭지'''

        loop_through_people(frame1, keypoints_with1) 
        camera_1 = results1['poses2d'].numpy()
       

        loop_through_people(frame2, keypoints_with2)
        camera_2 = results2['poses2d'].numpy()
        
        loop_through_people(frame3, keypoints_with3)
        camera_3 = results3['poses2d'].numpy()
        
        
        poly_list_1 = [(346, 623), (915,401), (714, 155), (169,92)]
        poly_1 = Polygon(poly_list_1)
        for a,person1  in enumerate(camera_1):
            left_x_1 = person1[7][0]
            left_y_1 = person1[7][1]
            right_x_1 = person1[8][0]
            right_y_1 = person1[8][1]
            front_x_1 = person1[10][0]/2 + person1[11][0]/2
            front_y_1 = person1[10][1]/2 + person1[11][1]/2


            trans_foot_1 = M1@(front_x_1 , front_y_1 , 1)
            trans_foot_1 = trans_foot_1/trans_foot_1[2]
            trans_x_1 = trans_foot_1[0]
            trans_y_1 = trans_foot_1[1]
            
            trans_right_1 = M1@(right_x_1 , right_y_1 , 1)
            trans_right_1 = trans_right_1/trans_right_1[2]
            tr_x_1 = trans_right_1[0]
            tr_y_1 = trans_right_1[1]

            trans_left_1 = M1@(left_x_1 , left_y_1 , 1)
            trans_left_1 = trans_left_1/trans_left_1[2]
            tl_x_1 = trans_left_1[0]
            tl_y_1 = trans_left_1[1]
            
           
            if poly_1.contains(Point(front_x_1 , front_y_1)) == True:

            #if xy_1[0] < 446 and xy_1[0] > 178 and xy_1[1] > 270 and xy_1[1] < 408: #before1 = np.float32([[346, 623],[915,401],[714, 155],[169,92]])
                pts1 = np.array([[tl_x_1,tl_y_1],[tr_x_1,tr_y_1],[trans_x_1,trans_y_1]], np.int32)
                ROI_image = cv2.circle(ROI_image,(int(trans_x_1),int(trans_y_1)), 3, (0,0,255), -1)
                ROI_image2 = cv2.polylines(ROI_image2, [pts1], True, (0,0,255), 1 )
                ROI_image2 = cv2.circle(ROI_image2,(int(trans_x_1),int(trans_y_1)), 2, (0,0,0), -1)


            
        
        poly_list_2 = [(942,709), (100,500), (197,306), (983,174)]
        poly_2 = Polygon(poly_list_2)
        for b,person2  in enumerate(camera_2):
            left_x_2 = person2[7][0]
            left_y_2 = person2[7][1]
            right_x_2 = person2[8][0]
            right_y_2 = person2[8][1]
            front_x_2 = person2[10][0]/2 + person2[11][0]/2
            front_y_2 = person2[10][1]/2 + person2[11][1]/2


            trans_foot_2 = M2@(front_x_2 , front_y_2 , 1)
            trans_foot_2 = trans_foot_2/trans_foot_2[2]
            trans_x_2 = trans_foot_2[0]
            trans_y_2 = trans_foot_2[1]


            trans_right_2 = M2@(right_x_2 , right_y_2 , 1)
            trans_right_2 = trans_right_2/trans_right_2[2]
            tr_x_2 = trans_right_2[0]
            tr_y_2 = trans_right_2[1]

            trans_left_2 = M2@(left_x_2 , left_y_2 , 1)
            trans_left_2 = trans_left_2/trans_left_2[2]
            tl_x_2 = trans_left_2[0]
            tl_y_2 = trans_left_2[1]
           
            
            if poly_2.contains(Point(front_x_2 , front_y_2)) == True:

            #if xy_1[0] < 446 and xy_1[0] > 178 and xy_1[1] > 270 and xy_1[1] < 408: #before1 = np.float32([[346, 623],[915,401],[714, 155],[169,92]])
                pts2 = np.array([[tl_x_2,tl_y_2],[tr_x_2,tr_y_2],[trans_x_2,trans_y_2]], np.int32)
                ROI_image = cv2.circle(ROI_image,(int(trans_x_2),int(trans_y_2)), 3, (0,255,0), -1)
                ROI_image2 = cv2.polylines(ROI_image2, [pts2], True, (0,255,0), 1 )
                ROI_image2 = cv2.circle(ROI_image2,(int(trans_x_2),int(trans_y_2)), 2, (0,0,0), -1)

        
        
        
        poly_list_3 = [(733,718), (203,542), (415,220), (935,131)]
        poly_3 = Polygon(poly_list_3)
        for c,person3  in enumerate(camera_3):
            left_x_3 = person3[7][0]
            left_y_3 = person3[7][1]
            right_x_3 = person3[8][0]
            right_y_3 = person3[8][1]
            front_x_3 = person3[10][0]/2 + person3[11][0]/2
            front_y_3 = person3[10][1]/2 + person3[11][1]/2


            trans_foot_3 = M3@(front_x_3 , front_y_3 , 1)
            trans_foot_3 = trans_foot_3/trans_foot_3[2]
            trans_x_3 = trans_foot_3[0]
            trans_y_3 = trans_foot_3[1]

            trans_right_3 = M3@(right_x_3 , right_y_3 , 1)
            trans_right_3 = trans_right_3/trans_right_3[2]
            tr_x_3 = trans_right_3[0]
            tr_y_3 = trans_right_3[1]

            trans_left_3 = M3@(left_x_3 , left_y_3 , 1)
            trans_left_3 = trans_left_3/trans_left_3[2]
            tl_x_3 = trans_left_3[0]
            tl_y_3 = trans_left_3[1]
           
            
            if poly_3.contains(Point(front_x_3 , front_y_3)) == True:

            #if xy_1[0] < 446 and xy_1[0] > 178 and xy_1[1] > 270 and xy_1[1] < 408: #before1 = np.float32([[346, 623],[915,401],[714, 155],[169,92]])
                pts3 = np.array([[tl_x_3,tl_y_3],[tr_x_3,tr_y_3],[trans_x_3,trans_y_3]], np.int32)
                ROI_image = cv2.circle(ROI_image,(int(trans_x_3),int(trans_y_3)), 3, (255,0,0), -1)
                ROI_image2 = cv2.polylines(ROI_image2, [pts3], True, (255,0,0), 1)
                ROI_image2 = cv2.circle(ROI_image2,(int(trans_x_3),int(trans_y_3)), 2, (0,0,0), -1)
                

        resize_frame1 = cv2.resize(frame1, (320, 180))
        resize_frame2 = cv2.resize(frame2, (320, 180))
        resize_frame3 = cv2.resize(frame3, (320, 180))
        resize_ROI_image = cv2.resize(ROI_image, (960,540) )
        

        img_con = cv2.vconcat([resize_frame1, resize_frame2,resize_frame3])
        img_hcon = cv2.hconcat([img_con, resize_ROI_image])
    

        
        
        cv2.imshow('mapping', img_hcon)
        cv2.imshow('vector', ROI_image2)
        
        
        # 영상을 저장한다.
        out1.write(frame1)
        out2.write(frame2)
        out3.write(frame3)
        out4.write(img_hcon)
        out5.write(ROI_image2)
        
        # 1ms뒤에 뒤에 코드 실행해준다.
        k = cv2.waitKey(1) & 0xff
        #키보드 esc 누르면 종료된다.
        if k == 27:
            break
    video_capture1.release()  # cap 객체 해제
    video_capture2.release()  # cap 객체 해제
    video_capture3.release()  # cap 객체 해제
    out1.release()  # out 객체 해제
    out2.release()  # out 객체 해제
    out3.release()  # out 객체 해제
    out4.release()  # out 객체 해제
    out5.release()  # out 객체 해제
    cv2.destroyAllWindows()

if __name__ == "__main__":
    writeVideo()