In [1]:
#여기 코드가 가장 중요하다. 위의 코드를 사용하면 matplot창을 띄워주고
# 아래의 코드를 사용하면 파이썬에서 첫번째 이미지만 보여준다.


%matplotlib qt

#%matplotlib inline

In [2]:
import tensorflow as tf
import os

def download_model(model_type):
    server_prefix = 'https://omnomnom.vision.rwth-aachen.de/data/metrabs'
    model_zippath = tf.keras.utils.get_file(
        origin=f'{server_prefix}/{model_type}_20211019.zip',
        extract=True, cache_subdir='models')
    model_path = os.path.join(os.path.dirname(model_zippath), model_type)
    return model_path

model = tf.saved_model.load(download_model('metrabs_mob3l_y4t')) # or metrabs_eff2l_y4 for the big model
! wget -q https://raw.githubusercontent.com/isarandi/metrabs/master/img/test_image_3dpw.jpg


'wget'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


In [15]:
import cv2
image1 = cv2.imread('C:/Users/Leeyourack/jookyoung/image/2.screenshot/3scr239.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2RGB)
pred1 = model.detect_poses(image1, skeleton='smpl_24')

In [16]:
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from mpl_toolkits.mplot3d import Axes3D
import numpy as np 

def visualize(im, detections, poses3d, poses2d, edges):
    fig = plt.figure(figsize=(10, 5.2))
    image_ax = fig.add_subplot(1, 2, 1)
    image_ax.imshow(image1)
    for x, y, w, h in detections[:, :4]:
        image_ax.add_patch(Rectangle((x, y), w, h, fill=False))
    

    pose_ax = fig.add_subplot(1, 2, 2, projection='3d')
    pose_ax.view_init(5, -85)
    pose_ax.set_xlim3d(-10000, 1500)
    pose_ax.set_zlim3d(0, 6000)
    pose_ax.set_ylim3d(0, 20000)


    # x, y, z값 
    xpos = [-10000,-1500,500]
    ypos = [10000,9000,5000]
    zpos = [0,0,0]

    # delta x, y, z 값
    dx = [4000,2000,1000]
    dy = [10000,11000,15000]
    dz = [2000,2000,2000]

    #그래프 만들기
    pose_ax.bar3d(xpos,ypos,zpos,dx,dy,dz,'#7f7f7f',alpha=0.2) #,color='#00ceaa'(초록색) 기본값은 파란색
    pose_ax.set_title('6F')
    pose_ax.set_xlabel('x axis')
    pose_ax.set_ylabel('y axis')
    pose_ax.set_zlabel('z axis')

    '''#2
    pose_ax = fig.add_subplot(1, 2, 2, projection='3d')
    pose_ax.view_init(5, -85)
    pose_ax.set_xlim3d(-1500, 1500)
    pose_ax.set_zlim3d(-500, 1500)
    pose_ax.set_ylim3d(0, 3000)'''



    # Matplotlib plots the Z axis as vertical, but our poses have Y as the vertical axis.
    # Therefore, we do a 90° rotation around the X axis:
    poses3d[..., 1], poses3d[..., 2] = poses3d[..., 2], -poses3d[..., 1] 
    '''a=np.ones(24)*(-6000)
    b=np.ones(24)*(-1000)
    c=np.ones(24)*(+300)
    shift=np.row_stack((a,b,c))'''

    for pose3d, pose2d in zip(poses3d, poses2d):
        #p1=pose3d.T+shift
        for i_start, i_end in edges:
            image_ax.plot(*zip(pose2d[i_start], pose2d[i_end]), marker='o', markersize=2)
            pose_ax.plot(*zip(pose3d[i_start], pose3d[i_end]), marker='o', markersize=2)
        image_ax.scatter(*pose2d.T, s=2)
        pose_ax.scatter(*pose3d.T, s=2)

    fig.tight_layout()
    plt.show()

visualize(
    image1, 
    pred1['boxes'].numpy(),
    pred1['poses3d'].numpy(),
    pred1['poses2d'].numpy(),
    model.per_skeleton_joint_edges['smpl_24'].numpy())

In [17]:
import cv2
image2 = cv2.imread('C:/Users/Leeyourack/jookyoung/image/2.screenshot/3scr253.jpg')
image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)
pred2 = model.detect_poses(image2, skeleton='smpl_24')

In [18]:
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from mpl_toolkits.mplot3d import Axes3D
import numpy as np 

def visualize(im, detections, poses3d, poses2d, edges):
    fig = plt.figure(figsize=(10, 5.2))
    image_ax = fig.add_subplot(1, 2, 1)
    image_ax.imshow(image2)
    for x, y, w, h in detections[:, :4]:
        image_ax.add_patch(Rectangle((x, y), w, h, fill=False))
    

    pose_ax = fig.add_subplot(1, 2, 2, projection='3d')
    pose_ax.view_init(5, -85)
    pose_ax.set_xlim3d(-10000, 1500)
    pose_ax.set_zlim3d(0, 6000)
    pose_ax.set_ylim3d(0, 20000)


    # x, y, z값 
    xpos = [-10000,-1500,500]
    ypos = [10000,9000,5000]
    zpos = [0,0,0]

    # delta x, y, z 값
    dx = [4000,2000,1000]
    dy = [10000,11000,15000]
    dz = [2000,2000,2000]

    #그래프 만들기
    pose_ax.bar3d(xpos,ypos,zpos,dx,dy,dz,'#7f7f7f',alpha=0.2) #,color='#00ceaa'(초록색) 기본값은 파란색
    pose_ax.set_title('6F')
    pose_ax.set_xlabel('x axis')
    pose_ax.set_ylabel('y axis')
    pose_ax.set_zlabel('z axis')

    '''#2
    pose_ax = fig.add_subplot(1, 2, 2, projection='3d')
    pose_ax.view_init(5, -85)
    pose_ax.set_xlim3d(-1500, 1500)
    pose_ax.set_zlim3d(-500, 1500)
    pose_ax.set_ylim3d(0, 3000)'''



    # Matplotlib plots the Z axis as vertical, but our poses have Y as the vertical axis.
    # Therefore, we do a 90° rotation around the X axis:
    poses3d[..., 1], poses3d[..., 2] = poses3d[..., 2], -poses3d[..., 1] 
    '''a=np.ones(24)*(-6000)
    b=np.ones(24)*(-1000)
    c=np.ones(24)*(+300)
    shift=np.row_stack((a,b,c))'''

    for pose3d, pose2d in zip(poses3d, poses2d):
        #p1=pose3d.T+shift
        for i_start, i_end in edges:
            image_ax.plot(*zip(pose2d[i_start], pose2d[i_end]), marker='o', markersize=2)
            pose_ax.plot(*zip(pose3d[i_start], pose3d[i_end]), marker='o', markersize=2)
        image_ax.scatter(*pose2d.T, s=2)
        pose_ax.scatter(*pose3d.T, s=2)

    fig.tight_layout()
    plt.show()

visualize(
    image2, 
    pred2['boxes'].numpy(),
    pred2['poses3d'].numpy(),
    pred2['poses2d'].numpy(),
    model.per_skeleton_joint_edges['smpl_24'].numpy())

In [45]:
import cv2
image3 = cv2.imread('C:/Users/Leeyourack/jookyoung/image/2.screenshot/3scr299.jpg')
image3 = cv2.cvtColor(image3, cv2.COLOR_BGR2RGB)
pred3 = model.detect_poses(image3, skeleton='smpl_24')

In [20]:
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from mpl_toolkits.mplot3d import Axes3D
import numpy as np 

def visualize(im, detections, poses3d, poses2d, edges):
    fig = plt.figure(figsize=(10, 5.2))
    image_ax = fig.add_subplot(1, 2, 1)
    image_ax.imshow(image3)
    for x, y, w, h in detections[:, :4]:
        image_ax.add_patch(Rectangle((x, y), w, h, fill=False))
    

    pose_ax = fig.add_subplot(1, 2, 2, projection='3d')
    pose_ax.view_init(5, -85)
    pose_ax.set_xlim3d(-10000, 1500)
    pose_ax.set_zlim3d(0, 6000)
    pose_ax.set_ylim3d(0, 20000)


    # x, y, z값 
    xpos = [-10000,-1500,500]
    ypos = [10000,9000,5000]
    zpos = [0,0,0]

    # delta x, y, z 값
    dx = [4000,2000,1000]
    dy = [10000,11000,15000]
    dz = [2000,2000,2000]

    #그래프 만들기
    pose_ax.bar3d(xpos,ypos,zpos,dx,dy,dz,'#7f7f7f',alpha=0.2) #,color='#00ceaa'(초록색) 기본값은 파란색
    pose_ax.set_title('6F')
    pose_ax.set_xlabel('x axis')
    pose_ax.set_ylabel('y axis')
    pose_ax.set_zlabel('z axis')

    '''#2
    pose_ax = fig.add_subplot(1, 2, 2, projection='3d')
    pose_ax.view_init(5, -85)
    pose_ax.set_xlim3d(-1500, 1500)
    pose_ax.set_zlim3d(-500, 1500)
    pose_ax.set_ylim3d(0, 3000)'''



    # Matplotlib plots the Z axis as vertical, but our poses have Y as the vertical axis.
    # Therefore, we do a 90° rotation around the X axis:
    poses3d[..., 1], poses3d[..., 2] = poses3d[..., 2], -poses3d[..., 1] 
    '''a=np.ones(24)*(-6000)
    b=np.ones(24)*(-1000)
    c=np.ones(24)*(+300)
    shift=np.row_stack((a,b,c))'''

    for pose3d, pose2d in zip(poses3d, poses2d):
        #p1=pose3d.T+shift
        for i_start, i_end in edges:
            image_ax.plot(*zip(pose2d[i_start], pose2d[i_end]), marker='o', markersize=2)
            pose_ax.plot(*zip(pose3d[i_start], pose3d[i_end]), marker='o', markersize=2)
        image_ax.scatter(*pose2d.T, s=2)
        pose_ax.scatter(*pose3d.T, s=2)

    fig.tight_layout()
    plt.show()

visualize(
    image3, 
    pred3['boxes'].numpy(),
    pred3['poses3d'].numpy(),
    pred3['poses2d'].numpy(),
    model.per_skeleton_joint_edges['smpl_24'].numpy())

normal vector 구하기

n은 AB와 AC에 수직이다.

A,B,C점 구하기

In [40]:
poses3d1=pred1['poses3d'].numpy()[0]
poses3d1[..., 1], poses3d1[..., 2] = poses3d1[..., 2], -poses3d1[..., 1]

In [51]:
a=poses3d1[11]
a

array([-827.9, 7784.8,  954.2], dtype=float32)

In [41]:
poses3d2=pred2['poses3d'].numpy()[0]
poses3d2[..., 1], poses3d2[..., 2] = poses3d2[..., 2], -poses3d2[..., 1]

In [52]:
b=poses3d2[11]
b

array([-1509.4,  6361.6,   623. ], dtype=float32)

In [46]:
poses3d3=pred3['poses3d'].numpy()[0]
poses3d3[..., 1], poses3d3[..., 2] = poses3d3[..., 2], -poses3d3[..., 1]
 

In [53]:
c=poses3d3[11]
c

array([ 219.8 , 6348.  , -446.65], dtype=float32)

벡터 만들기

In [55]:
ab = b-a
print(ab)
ac = c-a
print(ac)

[ -681.5    -1423.1997  -331.2   ]
[ 1047.7001 -1436.7998 -1400.85  ]


법벡터 만들기

In [61]:
list = [ab[1]*ac[2]-ab[2]*ac[1],-(ab[0]*ac[2]-ab[2]*ac[0]),ab[0]*ac[1]-ab[1]*ac[0]]
list

[1517821.1, -1301677.5, 2470265.5]

법벡터는 크기는 상관없다. 방향만 

In [63]:
list = [(ab[1]*ac[2]-ab[2]*ac[1])/100000,
        -(ab[0]*ac[2]-ab[2]*ac[0])/100000,
            (ab[0]*ac[1]-ab[1]*ac[0])/100000]
list

[15.17821125, -13.016775, 24.702655]

법벡터를 구했으니 얼만큼 회전해야 할지 알수있다.